package com.example.insurancefraudapp.ui.theme

import androidx.compose.ui.graphics.Color

// Core Foundation
val Primary = Color(0xFF00102A)
val OnPrimary = Color(0xFFFFFFFF)
val PrimaryContainer = Color(0xFF0F2546)
val OnPrimaryContainer = Color(0xFF798DB3)
val InversePrimary = Color(0xFFB3C7F0)
val Secondary = Color(0xFF30628E)
val OnSecondary = Color(0xFFFFFFFF)
val SecondaryContainer = Color(0xFF9FCDFF)
val OnSecondaryContainer = Color(0xFF245783)
val Tertiary = Color(0xFF001503)
val OnTertiary = Color(0xFFFFFFFF)
val TertiaryContainer = Color(0xFF002D0B)
val OnTertiaryContainer = Color(0xFF439F50)

// Surfaces
val Background = Color(0xFFF6FAFF)
val Surface = Color(0xFFF6FAFF)
val SurfaceDim = Color(0xFFD2DBE4)
val SurfaceBright = Color(0xFFF6FAFF)
val SurfaceContainerLowest = Color(0xFFFFFFFF)
val SurfaceContainerLow = Color(0xFFECF5FE)
val SurfaceContainer = Color(0xFFE6EFF8)
val SurfaceContainerHigh = Color(0xFFE0E9F2)
val SurfaceContainerHighest = Color(0xFFDBE4ED)
val OnSurface = Color(0xFF141D23)
val OnSurfaceVariant = Color(0xFF44474E)
val InverseSurface = Color(0xFF293138)
val InverseOnSurface = Color(0xFFE9F2FB)
val Outline = Color(0xFF75777F)
val OutlineVariant = Color(0xFFC4C6CF)
val SurfaceTint = Color(0xFF4B5F83)
val SurfaceVariant = Color(0xFFDBE4ED)

// Error
val Error = Color(0xFFBA1A1A)
val OnError = Color(0xFFFFFFFF)
val ErrorContainer = Color(0xFFFFDAD6)
val OnErrorContainer = Color(0xFF93000A)

// Fixed colors
val PrimaryFixed = Color(0xFFD7E3FF)
val PrimaryFixedDim = Color(0xFFB3C7F0)
val OnPrimaryFixed = Color(0xFF031B3C)
val OnPrimaryFixedVariant = Color(0xFF33476A)
val SecondaryFixed = Color(0xFFCFE5FF)
val SecondaryFixedDim = Color(0xFF9CCBFD)
val OnSecondaryFixed = Color(0xFF001D34)
val OnSecondaryFixedVariant = Color(0xFF104A75)
val TertiaryFixed = Color(0xFF99F89E)
val TertiaryFixedDim = Color(0xFF7EDB85)
val OnTertiaryFixed = Color(0xFF002106)
val OnTertiaryFixedVariant = Color(0xFF00531B)

// Risk Tier Semantics
val RiskHighBase = Color(0xFFDC2626)
val RiskHighContainer = Color(0xFFFEE2E2)
val RiskHighText = Color(0xFF991B1B)
val RiskHighBorder = Color(0xFFFCA5A5)
val RiskMediumBase = Color(0xFFD97706)
val RiskMediumContainer = Color(0xFFFEF3C7)
val RiskMediumText = Color(0xFF92400E)
val RiskMediumBorder = Color(0xFFFCD34D)
val RiskLowBase = Color(0xFF1E7E34)
val RiskLowContainer = Color(0xFFE8F5E9)
val RiskLowText = Color(0xFF0E5A20)
val RiskLowBorder = Color(0xFFA5D6A7)